/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacion;

import cjproyecto.basedatos;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luis Carlos Sanchez Nuñez
 */
public class appdieta extends javax.swing.JFrame {

    /**
     * Creates new form app
     */
    public appdieta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        calmin = new javax.swing.JTextField();
        mostrar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        bmin = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtarea = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        mdietas = new javax.swing.JButton();
        btninicio = new javax.swing.JButton();
        btncalc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dietas");
        setLocation(new java.awt.Point(350, 200));
        setSize(new java.awt.Dimension(1001, 559));

        jLabel6.setText("Introduza kCal dieta");

        mostrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mostrar.setText("Mostrar");
        mostrar.setToolTipText("");
        mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarActionPerformed(evt);
            }
        });

        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabla1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(tabla1);

        bmin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bmin.setText("Mostrar");
        bmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bminActionPerformed(evt);
            }
        });

        txtarea.setColumns(20);
        txtarea.setRows(5);
        txtarea.setPreferredSize(new java.awt.Dimension(180, 100));
        jScrollPane1.setViewportView(txtarea);

        jLabel7.setText("Visualizar todos los alimentos");

        jLabel8.setText("Visualizar todas las dietas");

        mdietas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mdietas.setText("Mostrar");
        mdietas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mdietasActionPerformed(evt);
            }
        });

        btninicio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btninicio.setText("Inicio");
        btninicio.setToolTipText("");
        btninicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninicioActionPerformed(evt);
            }
        });

        btncalc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btncalc.setText("Calculadora");
        btncalc.setToolTipText("");
        btncalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8)
                    .addComponent(calmin)
                    .addComponent(jLabel6)
                    .addComponent(bmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mdietas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 773, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btninicio, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btncalc, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(20, 20, 20)
                        .addComponent(mdietas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(20, 20, 20)
                        .addComponent(calmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(bmin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btninicio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncalc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarActionPerformed
        
        //Mostar todos los alimentos en tabla
     DefaultTableModel modelo = new DefaultTableModel();
    
         // Creamos las columnas.
         modelo.addColumn("Tipo");
         modelo.addColumn("Nombre");
         modelo.addColumn("Calorias");
         modelo.addColumn("Carbohidratos");
         modelo.addColumn("Proteinas");
         modelo.addColumn("Grasas");
        
    try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection conexion = DriverManager.getConnection("jdbc:mysql://localhost/proyectocj","root","");
                String sql = "select * from alimentos";
                Statement sentencia =conexion.createStatement();
                ResultSet resultado = sentencia.executeQuery(sql);

        while(resultado.next()){
           //Array para crear columnas
                Object [] datos = new Object[6];
                for (int i = 0; i < 6; i++) {
                    datos[i] = resultado.getObject(i+1);
                }
                modelo.addRow(datos);
              }

        tabla1.setModel(modelo);
                
        tabla1.getColumn("Tipo").setPreferredWidth(120);
        tabla1.getColumn("Nombre").setPreferredWidth(230);
        tabla1.getColumn("Calorias").setPreferredWidth(100);
        tabla1.getColumn("Carbohidratos").setPreferredWidth(100);
        tabla1.getColumn("Proteinas").setPreferredWidth(100);
        tabla1.getColumn("Grasas").setPreferredWidth(100);
           
        sentencia.close();
                conexion.close();
                
        } catch (SQLException | ClassNotFoundException ex) 
        {
            Logger.getLogger(appdieta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mostrarActionPerformed

    private void bminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bminActionPerformed
      
        //Mostrar dietas segun cantidad introducida
        basedatos b = new basedatos();
        try {
            txtarea.setText(b.listar(Double.parseDouble(calmin.getText())));
            txtarea.append("");
        } catch (NumberFormatException e) 
        {
            JOptionPane.showMessageDialog(null, "Introduzca una cantidad valida", "Error", JOptionPane.WARNING_MESSAGE);
            Logger.getLogger(appdieta.class.getName()).log(Level.SEVERE,null,e);
        }
        
    }//GEN-LAST:event_bminActionPerformed

    private void mdietasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mdietasActionPerformed
       
        //Mostrar dietas existentes   
        basedatos b = new basedatos();
        try {
            txtarea.append("");
            txtarea.setText(b.listardietas());
        } catch (NumberFormatException e) 
        {
            JOptionPane.showMessageDialog(null, "No es posible conectar con base de datos", "Error", JOptionPane.WARNING_MESSAGE);
            Logger.getLogger(appdieta.class.getName()).log(Level.SEVERE,null,e);
        }
        
    }//GEN-LAST:event_mdietasActionPerformed

    private void btninicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninicioActionPerformed
        
        //Boton para navegar hasta ventana inicio
        dispose();
        appmain ini=new appmain();
        ini.setLocationRelativeTo(null);
        ini.setVisible(true);   
        
    }//GEN-LAST:event_btninicioActionPerformed

    private void btncalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalcActionPerformed
       
        //Boton para navegar hasta ventana calculadora
        dispose();
        appcalc ini=new appcalc();
        ini.setLocationRelativeTo(null);
        ini.setVisible(true);   
        
    }//GEN-LAST:event_btncalcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(appdieta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(appdieta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(appdieta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(appdieta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new appdieta().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bmin;
    private javax.swing.JButton btncalc;
    private javax.swing.JButton btninicio;
    private javax.swing.JTextField calmin;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton mdietas;
    private javax.swing.JButton mostrar;
    private javax.swing.JTable tabla1;
    private javax.swing.JTextArea txtarea;
    // End of variables declaration//GEN-END:variables
}
